### ISSUE TITLE
Getting a couple of errors when checking this in the console. Any guidance appreciated.

### ISSUE THREAD

**Issue by rfikki** [SilentCicero/meteor-dapp-boilerplate#2]
http://localhost:3000/packages/ethereum_web3.js?6eb7f7927c94ee7c887d8b1303ce4d32e2190c29 is being assigned a //# sourceMappingURL, but already has one ethereum_web3.js:6625:4

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ ethereum_web3.js:2924:0

Also what is the suggested policy for adding server startup code? Is that added to the client/index.js file?
or is it better to make a separate server directory and add it there?

**Comment by SilentCicero** [comment]
I believe this comes with the territory of using xhr XMLHTTPRequests. I think this is more with web3 than this repo.
